#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    rightLineSensor, sensorLineFollower)
#pragma config(Sensor, in6,    leftLineSensor, sensorLineFollower)
#pragma config(Sensor, in8,    lightEmittingDiode, sensorAnalog)
#pragma config(Sensor, dgtl1,  ultrasoundInput, sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  rightTouchSensor, sensorTouch)
#pragma config(Sensor, dgtl6,  leftTouchSensor, sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           backRightMotor, tmotorVex393_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           frontLeftMotor, tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           extensionMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           turntableMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontRightMotor, tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port10,          backLeftMotor, tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stopAll() //stops all base motors
{
	motor[frontRightMotor] = 0;
	motor[frontLeftMotor]  = 0;
	motor[backLeftMotor]  = 0;
	motor[backRightMotor]  = 0;
}

task main ()
{

	//while(vexRT[Btn7D] == 0)
	//{
	//}

	while(1 == 1)
	{
		motor[frontRightMotor] = vexRT[Ch2] /2;
		motor[frontLeftMotor] = vexRT[Ch3] /2;
		motor[backLeftMotor] = vexRT[Ch3] /2;
		motor[backRightMotor] = vexRT[Ch2] /2;

		if(vexRT[Btn6D] == 1 && vexRT[Btn6U] == 0) //button 5U is pressed so claw opens
		{
			motor[clawMotor] = 100;
		}

		else if(vexRT[Btn6U] == 1 & vexRT[Btn6D] == 0) //button 5D is pressed and claw closes
		{
			motor[clawMotor] = -100;
		}
		else
		{
			motor[clawMotor] = 0; //if anything else happens, the claw motor doesn't move
			//}
		}

		stopAll();
	
		if(vexRT[Btn5U] == 1 && vexRT[Btn5D] == 0)
		{
			motor[extensionMotor] = 100;
		}
		else if(vexRT[Btn5D] == 1 && vexRT[Btn5U] == 0)
		{
			motor[extensionMotor] = -100;
		}
		else
		{
			motor[extensionMotor] = 0;
		}
		
		
		if(vexRT[Btn8L] == 1 & vexRT[Btn8R] == 0)
		{
			motor[turntableMotor] = 50;
		}
		else if(vexRT[Btn8R] == 1 & vexRT[Btn8L] == 0)
		{
			motor[turntableMotor] = -50;
		}
		else
		{
			motor[turntableMotor] = 0;
		}

	}
}
